Commit 4: ..of the kernel-src-tree patches
Signed-off-by: Kaiwan N Billimoria <kaiwan.billimoria@gmail.com>

diff --git a/do_stanly b/do_stanly
--- a/do_stanly
+++ b/do_stanly
@@ -18,6 +18,19 @@
 # [+] report file cleanup
 # [ ] Tools curr not working:
 #    [ ] scan-build
+# [ ] More static analysers for ksrc tree !?
+# $ make help
+# Static analysers:
+# [ ] checkstack      - Generate a list of stack hogs
+# [ ] namespacecheck  - Name space analysis on compiled kernel
+# [ ] versioncheck    - Sanity check on version.h usage
+# [ ] includecheck    - Check for duplicate included header files
+# [ ] export_report   - List the usages of all exported symbols
+# [ ] headers_check   - Sanity check on exported headers
+# [ ] headerdep       - Detect inclusion cycles in headers
+# [+]  coccicheck      - Check with Coccinelle
+# 
+#
 # [ ] make menuconfig interface
 #  
 # Ref: https://elinux.org/images/d/d3/Bargmann.pdf
@@ -49,6 +62,8 @@ parent=$(ps -o comm= $PPID)
 gKSRC=/lib/modules/$(uname -r)/build/   # kernel source tree (kernel-headers)
 gSMATCH_LOC=~/tools_local/smatch        # RELOOK- smatch tool location; /usr/local/bin ... ?
 
+FAILURE_MSG="returned a 'fail' value"
+
 ########### Functions follow #######################
 
 Warn()
@@ -59,60 +74,96 @@ Warn()
 # $1 : -q => quiet mode
 mkclean()
 {
-  [ ${KSRCTREE} -eq 1 ] && return
+  [ ${KSRCTREE_MODE} -eq 1 ] && {
+   [ "$1" != "-q" ] && echo " No 'make clean' in kernel src tree mode"
+   return
+  }
   local cmd="make clean"
   [ "$1" != "-q" ] && becho "[+] ${cmd}"
-  eval "${cmd}" > /dev/null || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' failed"
+  eval "${cmd}" > /dev/null || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' ${FAILURE_MSG}"
 }
 
-# Parameter: $1 = kernel src tree root
 checkpatch_check()
 {
   local cmd
   pwd
-  local files=$(find . -maxdepth 1 -name "*.[ch]" |tr "\n" " ")
+  # We do have to recurse here! Only the 'make <target>' targets auto-recurse
+  local files=$(find . -name "*.[ch]" |tr "\n" " ")
+  #local files=$(find . -maxdepth 1 -name "*.[ch]" |tr "\n" " ")
+  local numfiles=$(echo ${files}|wc -w)
 
-  [ ${KSRCTREE} -eq 1 ] && \
-    cmd="${1}/scripts/checkpatch.pl --root=${1} --file ${files}" || \
+  becho "${CMD_MSGPFX}" ; echo " Tool # ${1}"
+  [ ${KSRCTREE_MODE} -eq 1 ] &&
+    cmd="${KTREEROOT}/scripts/checkpatch.pl --root=${KTREEROOT} --file ${files}" || \
     cmd="${gKSRC}/scripts/checkpatch.pl --no-tree --file ${files}"
   mkclean -q
-  becho "[+] checkpatch.pl: ${cmd}"
+  becho "[+] checkpatch.pl: ${cmd}
+# of files to process: ${numfiles}"
   #echo " cmd = $cmd"
-  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' failed"
+  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' ${FAILURE_MSG}"
 }
 
 sparse_check()
 {
-  local cmd="make C=1 CHECK=\"$(which sparse)\""
+  local cmd
   mkclean -q
-  becho "[+] sparse: ${cmd}"
-  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' failed"
+
+  becho "${CMD_MSGPFX}" ; echo " Tool # ${1}"
+  [ ${KSRCTREE_MODE} -eq 1 ] && {
+   # '$(pwd)/' : the ending '/' is critical!
+   cmd="make C=1 CHECK=\"$(which sparse)\" $(pwd)/"
+   becho "[+] sparse: ${cmd}"
+   (
+   cd ${KTREEROOT}
+   eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' ${FAILURE_MSG}"
+   )
+  } || {
+   cmd="make C=1 CHECK=\"$(which sparse)\""
+   becho "[+] sparse: ${cmd}"
+   eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' ${FAILURE_MSG}"
+  }
 }
 
 gccwarn1_check()
 {
-  local cmd="make W=1"
+  local cmd
   mkclean -q
-  becho "[+] gcc : ${cmd} 'generally useful warnings'"
-  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' failed"
+
+  becho "${CMD_MSGPFX}" ; echo " Tool # ${1}"
+  [ ${KSRCTREE_MODE} -eq 1 ] && {
+   cmd="make W=1 $(pwd)/"
+   becho "[+] gcc : ${cmd} : 'generally useful warnings'"
+   #pwd
+   (
+   cd ${KTREEROOT}
+   #pwd
+   eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' returned a 'fail' value"
+   )
+  } || {
+   cmd="make W=1"
+   becho "[+] gcc : ${cmd} 'generally useful warnings'"
+   eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' returned a 'fail' value"
+  }
 }
 
 # usually overkill
 gccwarn12_check()
 {
   local cmd="make W=12"
+  becho "${CMD_MSGPFX}" ; echo " Tool # ${1}"
   mkclean -q
   becho "[+] gcc : ${cmd} 'possibly useful warnings'"
-  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' failed"
+  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' ${FAILURE_MSG}"
 }
 
 clang_check()
 {
   local cmd="make -skj20 CC=$(which clang)"
    # make: -s=silent, -k=keep-going, -j# of jobs
+  becho "${CMD_MSGPFX}" ; echo " Tool # ${1}"
   mkclean -q
   becho "[+] clang: ${cmd}"
-  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' failed"
+  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' ${FAILURE_MSG}"
 }
 
 # Uses a wrapper script 'coccichk'
@@ -122,51 +173,61 @@ clang_check()
 coccinelle_check()
 {
   # use '-v' parameter for verbose mode
-  local cmd="coccichk ."
+  local cmd="coccichk $(pwd)/"
+  becho "${CMD_MSGPFX}" ; echo " Tool # ${1}"
   mkclean -q
   becho "[+] coccinelle: ${cmd}"
+  echo " coccichk location: $(which coccichk)"
   echo "On $(pwd)"
-  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' failed"
+  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' ${FAILURE_MSG}"
 }
 
 smatch_check()
 {
  # Ref: http://smatch.sourceforge.net/
   local cmd="make CHECK=\"${gSMATCH_LOC}/smatch -p=kernel\" C=1"
+  becho "${CMD_MSGPFX}" ; echo " Tool # ${1}"
   mkclean -q
   becho "[+] smatch: ${cmd}"
-  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' failed"
+  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' ${FAILURE_MSG}"
 }
 
 # TODO : Not working ok; fails with:
 #  "cc1: error: code model kernel does not support PIC mode" ??
 scan-build_check()
 {
+  becho "${CMD_MSGPFX}" ; echo " Tool # ${1}"
  # Ref: https://clang-analyzer.llvm.org/scan-build.html
   mkclean -q
   local cmd="scan-build -v --use-analyzer=/usr/bin/gcc make"
   becho "[+] ${cmd}"
-  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' failed"
+  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' ${FAILURE_MSG}"
 }
 
 flawfinder_check()
 {
   mkclean -q
   local cmd="flawfinder --quiet *.[ch]"
+  becho "${CMD_MSGPFX}" ; echo " Tool # ${1}"
   becho "[+] ${cmd}"
   echo "On $(pwd)"
-  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' failed"
+  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' ${FAILURE_MSG}"
 }
 
-# $1 : -q => quiet mode
+# $1 : -q => quiet mode [optional]
+# $2 : tool number
 cppcheck_check()
 {
+  local tooln=$1
   mkclean -q
   local cmd="cppcheck -v ."
-  [ "$1" = "-q" ] && cmd="cppcheck -q -v ."
+  [ $# -eq 2 -a "$1" = "-q" ] && {
+    cmd="cppcheck -q -v ." ; tooln=$2
+  }
+  becho "${CMD_MSGPFX}" ; echo " Tool # ${tooln}"
   becho "[+] ${cmd}"
   echo "On $(pwd)"
-  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' failed"
+  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' ${FAILURE_MSG}"
   mkclean -q
 }
 
@@ -177,9 +238,10 @@ xcc_test()
   mkclean -q
   local cmd="make ARCH=powerpc CROSS_COMPILE=powerpc64-linux-"
   [ "$1" = "-v" ] && cmd="make V=1 ARCH=powerpc CROSS_COMPILE=powerpc64-linux-"
+  becho "${CMD_MSGPFX}" ; echo " Tool # ${1}"
   becho "[+] ${cmd}"
   #echo "On $(pwd)"
-  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' failed"
+  eval "${cmd}" || Warn "*** $(pwd) : ${FUNCNAME[0]}(): cmd '${cmd}' ${FAILURE_MSG}"
   mkclean -q
 }
 
@@ -189,35 +251,90 @@ run_checkers()
   #echo "run_checkers(): PFX = ${PFX}"
   # In a sub-shell
   (   
+  local toolnum=1
+
   cd $1
   wecho "$(pwd)"
   mkclean -q
-  [ ${KSRCTREE} -eq 0 ] && ls -l | sed '1d'
+  [ ${KSRCTREE_MODE} -eq 0 ] && ls -l | sed '1d'
+
   echo
-  checkpatch_check ${KTREEROOT}
+  checkpatch_check ${toolnum}
+  let toolnum=toolnum+1
+
   echo
-  sparse_check
+  sparse_check ${toolnum}
+  let toolnum=toolnum+1
+
   echo
-  gccwarn1_check
+  gccwarn1_check ${toolnum}
+  let toolnum=toolnum+1
+
+  echo
+  #gccwarn12_check ${toolnum}  # overkill
+  #let toolnum=toolnum+1
+
   #echo
-  #gccwarn12_check   # overkill
-  echo
-  clang_check
+  #clang_check ${toolnum}
+  #let toolnum=toolnum+1
+
   #echo
-  #scan-build_check
+  #scan-build_check ${toolnum}
+  #let toolnum=toolnum+1
+
   echo
-  coccinelle_check
+  coccinelle_check ${toolnum}
+  let toolnum=toolnum+1
+
   echo
   [ ${SKIP_SMATCH} -eq 0 ] && {
-    smatch_check
+    smatch_check ${toolnum}
+    let toolnum=toolnum+1
     echo
   }
-  flawfinder_check
+
+  flawfinder_check ${toolnum}
+  let toolnum=toolnum+1
+
   echo
-  cppcheck_check -q
+  cppcheck_check -q ${toolnum}
+  let toolnum=toolnum+1
+
   echo
-  [ ${SKIP_XCC} -eq 0 ] && xcc_test
+  [ ${SKIP_XCC} -eq 0 ] && {
+    xcc_test ${toolnum}
+    let toolnum=toolnum+1
+  }
+
+  becho "Total tool runs: $((${toolnum}-1))"
   ) # sub-shell end
+}
+
+start_analysis()
+{
+local dir
+
+# For out-of-tree kernel module code, recursively iterate over each dir
+[ ${KSRCTREE_MODE} -eq 0 ] && {
+for dir in $(find ${gSRC} -type d \
+ -not -path "*.git*" -not -path "*.tmp_versions" -not -path "*tools") # RELOOK: why not 'tools*'?
+do
+  #echo "In $dir:"
+  [ ! -f $dir/Makefile ] && {
+    aecho "[!] Skipping '$dir', no Makefile..."
+    continue
+  }
+  echo "-----------------------------------------------------------"
+  wecho "$(date)"
+  run_checkers $dir
+  echo
+done
+} ||  {
+# kernel-src-tree mode; the kbuild framework is a recursive one!
+ echo "-----------------------------------------------------------"
+ wecho "$(date)"
+ run_checkers ${gSRC}
+}
 }
 
 tools_check()
@@ -246,12 +363,13 @@ tools_check()
    echo "${name}: 'spatch' missing, pl install the 'coccinelle' package"
    exit 1
  }
- # TODO : 'coccichk' to be installed into /usr/local/bin (or ~/bin) on first run
+ # 'coccichk' to be installed into /usr/local/bin (or ~/bin) on first run
+ echo "coccichk location: $(which coccichk)"
  which coccichk >/dev/null || {
-   echo "${name}: (local) <...>/stanly/coccichk wrapper script missing (or not in PATH), pl install"
-   echo "Tip: sudo cp <...>/stanly/coccichk /usr/local/bin
-and add /usr/local/bin to the PATH env var"
-   exit 1
+   echo "${name}: (local) <...>/stanly/coccichk wrapper script missing (or not in PATH), will install now..."
+   #echo "Tip: sudo cp <...>/stanly/coccichk /usr/local/bin
+#and add /usr/local/bin to the PATH env var"
+   sudo cp ${PFX}/coccichk /usr/local/bin || exit 1
  }
 
  SKIP_SMATCH=0
@@ -278,40 +396,30 @@ and add /usr/local/bin to the PATH env var"
  echo " [.] OK"
 }
 
-start()
-{
-gSRC=$1
-
-IFS=$'\n'; set -f
-for d in $(find ${gSRC} -type d \
- -not -path "*.git*" -not -path "*.tmp_versions" -not -path "*tools") # RELOOK: why not 'tools*'?
-do
-  #echo "In $d:"
-  [ ! -f $d/Makefile ] && {
-    aecho "[!] Skipping '$d', no Makefile..."
-    continue
-  }
-  echo "-----------------------------------------------------------"
-  wecho "$(date)"
-  run_checkers $d
-  echo
-done
-
-unset IFS; set +f
-}
-
 
 ##### 'main' #####
-
 PFX=$(dirname $(which $0))    # dir in which 'stanly' and tools reside
 source ${PFX}/common.sh || {
  echo "${name}: fatal: could not source ${PFX}/common.sh , aborting..."
  exit 1
 }
 
+[ $# -lt 2 ] && {
+ echo "Usage: ${name}  dir-to-scan kernel-src-tree-mode[0|1] [kernel-src-tree-root]"
+ echo "Tip: only invoke this script from the 'stanly' wrapper script."
+ exit 1
+}
+# 3 parameters received; passed along by 'stanly' wrapper
+#  dir-to-scan kernel-src-tree-mode[0|1] [kernel-src-tree-root]
+# Keep these global.
+export gSRC=$1
+export KSRCTREE_MODE=$2
+[ ${KSRCTREE_MODE} -eq 1 ] && export KTREEROOT=$3
+[ ${KSRCTREE_MODE} -eq 1 ] &&
+  CMD_MSGPFX="+---------------- kernel-src-tree mode ----------------+" ||
+  CMD_MSGPFX="+---------------- out-of-tree mode ----------------+"
+
 techo "<<<<<<<<<<<<<<<< stanly : a static analysis tool integrator >>>>>>>>>>>>>>>>"
-KSRCTREE=$2   # passed from our 'stanly' wrapper
-[ ${KSRCTREE} -eq 1 ] && KTREEROOT=$3   # passed from our 'stanly' wrapper
 tools_check
-start ${1}
+start_analysis
 echo "|- End Run : $(date) -|"
