Move 'usage' checking right to the top
Signed-off-by: Kaiwan N Billimoria <kaiwan.billimoria@gmail.com>

diff --git a/stanly b/stanly
--- a/stanly
+++ b/stanly
@@ -14,9 +14,27 @@
 # kaiwan -at- kaiwantech -dot- com
 # 
 # License: MIT.
-# 
 name=$(basename $0)
-PFX=$(dirname `which $0`)
+[ $# -ne 1 ] && {
+  echo "Usage: ${name} path-to-codebase-to-check"
+  exit 1
+}
+[ ! -d $1 ] && {
+  echo "${name}: path-to-codebase-to-check \"$1\" invalid?"
+  exit 1
+}
+
+#PFX=$(pwd)
+PFX=$(dirname $(which $0))    # dir in which 'stanly' and tools reside
+#  echo " PFX = ${PFX} basename = $(basename ${PFX})"
+#  base=$(basename ${PFX})
+#  if [ "${base}" = "stanly" ] ; then # running from stanly folder
+#    PFX=.
+#  else
+#    PFX=${STANLY_INSTALL_FOLDER}
+#  fi
+#  exit 0
+
 source ${PFX}/common.sh || {
  echo "${name}: fatal: could not source ${PFX}/common.sh , aborting..."
  exit 1
